import Head from 'next/head'
import Image from 'next/image'
import headerStyles from '../styles/Header.module.css'
import bookArticleHeaderStyles from '../styles/BookArticleHeader.module.css'
import IconKebabMenuStyles from '../styles/IconKebabMenu.module.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header class={headerStyles.Header}>
        <div className={headerStyles.Header_icon}>
          <a>
            <Image src="/images/icons/noun_back_icon.svg" height={30} width={30} alt="back arrow by Тимур Минвалеев from the thenounproject.com" />
          </a>
        </div>
        <h1 class={headerStyles.Header_title}>Title Here</h1>
        <div className={headerStyles.Header_icon}>
          <button>
            <span className={IconKebabMenuStyles.IconKebabMenu}>
              <span></span>
              <span></span>
              <span></span>
            </span>
          </button>
        </div>
      </header>

      <main>
        <article>
          <header className={bookArticleHeaderStyles.BookArticleHeader}>
            <div className={bookArticleHeaderStyles.BookArticleHeader_imageContainer}>
              <Image src="/images/bookcover.jpg" alt="Distorted book cover" width={327} height={500} className={bookArticleHeaderStyles.BookArticleHeader_image} />
            </div>
            <div className={bookArticleHeaderStyles.BookArticleHeader_info}>
              <h2>Distorted</h2>
              <h3>Alabaster Penitentiary, Volume 1</h3>
              <dl className={bookArticleHeaderStyles.BookArticleHeader_details}>
                <div>
                  <dt>Author:</dt>
                  <dd>Nyla K</dd>
                </div>
                <div>
                  <dt>Published:</dt>
                  <dd>18 Mar. 2021</dd>
                </div>
              </dl>
            </div>
            <div className={bookArticleHeaderStyles.BookArticleHeader_rating}>
              <span className={bookArticleHeaderStyles.BookArticleHeader_ratingNum}>4.3</span>
              <span className={bookArticleHeaderStyles.BookArticleHeader_ratingStars}>Stars</span>
            </div>
          </header>
          <nav></nav>
          <section></section>
        </article>
      </main>
    </>
  )
}
