import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Boc</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla nisi et arcu tempus dignissim. Maecenas tincidunt malesuada erat, in congue odio commodo nec. Mauris est sapien, pretium non maximus et, porta sed dolor. Quisque neque ligula, bibendum sit amet molestie at, ornare nec elit. Sed quis neque id nunc mattis cursus. In malesuada eros ante, ut aliquam leo tincidunt non. Sed id mollis massa. Nulla tempus non magna in interdum. Phasellus at nisi dolor. Quisque vel enim ornare ipsum lobortis condimentum. Cras ultrices a diam non vestibulum. Sed ut consequat ante.</p>
      </main>
    </div>
  )
}
