import Head from 'next/head'
import Image from 'next/image'
import headerStyles from '../styles/Header.module.css'
import bookArticleHeaderStyles from '../styles/BookArticleHeader.module.css'
import IconKebabMenuStyles from '../styles/IconKebabMenu.module.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header class={headerStyles.Header}>
        <div className={headerStyles.Header_icon}>
          <a>
            <Image src="/images/icons/noun_back_icon.svg" height={30} width={30} alt="back arrow by Тимур Минвалеев from the thenounproject.com" />
          </a>
        </div>
        <h1 class={headerStyles.Header_title}></h1>
        <div className={headerStyles.Header_icon}>
          <button>
            <span className={IconKebabMenuStyles.IconKebabMenu}>
              <span></span>
              <span></span>
              <span></span>
            </span>
          </button>
        </div>
      </header>

      <main>
        <article>
          <header className={bookArticleHeaderStyles.BookArticleHeader}>
            <div className={bookArticleHeaderStyles.BookArticleHeader_imageContainer}>
              <Image src="/images/bookcover2.jpg" alt="Book cover" width={327} height={500} className={bookArticleHeaderStyles.BookArticleHeader_image} />
            </div>
            <div className={bookArticleHeaderStyles.BookArticleHeader_info}>
              <h2>Hunters and Killers: Serial Killers</h2>
              <h3>(Criminal Delights Book 13)</h3>
              <dl className={bookArticleHeaderStyles.BookArticleHeader_details}>
                <div>
                  <dt>Author(s):</dt>
                  <dd>Dora Esquivel, Natasha Snow, Miranda Vescio, Alexa Wayne</dd>
                </div>
                <div>
                  <dt>Published:</dt>
                  <dd>24 May 2019</dd>
                </div>
              </dl>
            </div>
            <div className={bookArticleHeaderStyles.BookArticleHeader_rating}>
              <span className={bookArticleHeaderStyles.BookArticleHeader_ratingNum} aria-hidden="true">3.5</span>
              <span className={bookArticleHeaderStyles.BookArticleHeader_ratingStars} data-highlight-stars="3.5" aria-hidden="true">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
              </span>
              <span className="visually-hidden">
                Average rating of 3.5 stars out of 5
              </span>
            </div>
          </header>
          <nav></nav>
          <section></section>
        </article>
      </main>
    </>
  )
}
